development:
  host: localhost:8080
  email: jason.gonzales23@gmail.com
  password: plaster23
staging:
  host: staging.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
